version: "3.9"

services:
  goapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MAX_IP_REQUESTS_PER_SECOND=10
      - MAX_TOKEN_REQUESTS_PER_SECOND=100
      - TIME_BLOCK_IN_SECOND=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./.env:/.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
